name: Deploy to Code Engine

on:
  push:
    branches: [ '**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Build and Deploy to Code Engine
      uses: IBM/code-engine-github-action@v1
      with:
        api-key: ${{ secrets.IBM_CLOUD_API_KEY }}
        resource-group: 'Default'
        region: 'ca-tor'
        project: 'checkmate'
        name: 'checkmate'
        component: 'app'
        build-source: './' 
        build-strategy: 'dockerfile'
        # CHANGED TO ca.icr.io
        image: 'ca.icr.io/checkmate-registry/checkmate:latest'
        registry-secret: 'ce-auto-icr-private-tor'
        cpu: 1
        memory: 4G